version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.4.0
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=fabric:2.1.0
        - CALIPER_BENCHCONFIG=benchmarks/myAssetBenchmark.yaml
        - CALIPER_NETWORKCONFIG=networks/networkConfig.yaml
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace